# Spring
spring.application.name: BackendForDemoAlenaProject

# Server
server:
  port: 18080

# Telegram
telegram:
    bot:
      token: ${DEMO_BOT_TOKEN}
      frontend-url: https://vnsemkin.github.io