services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - VIRTUAL_PORT=18080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  demo-backend:
    image: demo-backend:latest
    container_name: demo-backend
    restart: always
    environment:
      - VIRTUAL_HOST=easygo.duckdns.org
      - LETSENCRYPT_HOST=easygo.duckdns.org
      - LETSENCRYPT_EMAIL=vnsemkin@gmail.com
      - DEMO_BOT_TOKEN=${DEMO_BOT_TOKEN}
    expose:
      - "18080"

volumes:
  certs:
  vhost:
  html:
