services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - ../nginx/vhost.d:/etc/nginx/vhost.d:ro  # Replace the named volume with your directory
      - html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - ../nginx/vhost.d:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html

  demo-backend:
    image: demo-backend:latest
    container_name: demo-backend
    restart: always
    environment:
      - VIRTUAL_PORT=18080
      - VIRTUAL_HOST=easygo.duckdns.org
      - LETSENCRYPT_HOST=easygo.duckdns.org
      - LETSENCRYPT_EMAIL=vnsemkin@gmail.com
      - DEMO_BOT_TOKEN=${DEMO_BOT_TOKEN}
    expose:
      - "18080"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  certs:
  vhost:
  html:
