name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '23'

      - name: Build with Gradle
        run: gradle build -x test

      - name: Build Docker image
        run: docker build -t demo-backend:latest .

      - name: Save Docker image as tar file
        run: docker save demo-backend:latest > demo-backend.tar

      - name: Check tar file size
        run: ls -lh demo-backend.tar

      - name: Move tar file into folder
        run: |
          mkdir -p deploy
          mv demo-backend.tar deploy/

      # New step: Clear remote /tmp/deploy folder before copy
      - name: Clear remote /tmp/deploy folder
        uses: appleboy/ssh-action@master
        with:
          host: 95.179.242.147
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            rm -rf /tmp/deploy
            mkdir -p /tmp/deploy

      - name: Copy Docker image to remote server
        uses: appleboy/scp-action@master
        with:
          host: 95.179.242.147
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          source: "deploy/demo-backend.tar"
          target: "/tmp/deploy/demo-backend.tar"
          timeout: 300s
          proxy_timeout: 180s

      - name: Deploy Docker container on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 95.179.242.147
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            docker load -i /tmp/deploy/demo-backend.tar
            docker stop demo-backend || true
            docker rm demo-backend || true
            docker run -d --name demo-backend -p 8443:8443 demo-backend:latest
